version: '3.4'

services:
  seq:
    ports:
    - "5341:80"
    environment:
      - ACCEPT_EULA=Y

  trucks.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - EventBusConnection=rabbitmq
      - EventBusUserName=guest
      - EventBusPassword=guest
    ports:
      -  "55001:8080"
      -  "55002:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  
  trucks-history.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - EventBusConnection=rabbitmq
      - EventBusUserName=guest
      - EventBusPassword=guest
    ports:
      -  "55003:8080"
      -  "55004:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672" 
