version: '3.4'

services:
  seq:
    container_name: seq
    image: datalust/seq:latest
  
  rabbitmq:
    image: rabbitmq:3-management-alpine

  trucks-mssql:
    container_name: trucks-mssql
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Pass123!"
      ACCEPT_EULA: "Y"
    ports:
      - "5454:1433"

  trucks.api:
    image: ${DOCKER_REGISTRY-}trucksapi
    build:
      context: .
      dockerfile: services/trucks/trucks.api/Dockerfile
    environment:
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false

  trucks-history.api:
    image: ${DOCKER_REGISTRY-}truckshistoryapi
    build:
      context: .
      dockerfile: services/trucks-history/trucks-history.api/Dockerfile
    environment:
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
