version: '3.4'

services:
  trucks-mssql:
    container_name: trucks-mssql
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Pass123!"
      ACCEPT_EULA: "Y"
    ports:
      - "5454:1433"

  trucks.api:
    image: ${DOCKER_REGISTRY-}trucksapi
    build:
      context: .
      dockerfile: services/trucks/trucks.api/Dockerfile
